<?php
// Include the header.php file
include 'partials/header.php';
?>

<div class="grain container-fluid">
    <div class="container mt-5 mb-5">
        <p class="fw-bold mb-5 border-bottom mt-5">Home | Blog | Article | Mar 2024</p>

        <div class="row col-12 d-flex justify-content-center align-items-center">
            <div class="col-md-9">
                <img src="assets/images/events/2nd Internal SH/DAY1/20240327_1142.jpg" class="img-fluid" style="object-fit: cover; width: 100%; height: 200px;">
            </div>

            <div class="col-md-9">
                <p class="mt-3">April 2024 | Responsible Computing</p>
                <h2 class="mt-1 fw-bold">Report on the 2nd Internal Stakeholders Meeting</h2>

                <h3 class="mt-3 mb-3">Responsible Computing Project Feedback Session</h3>
                <p class="fw-bold"> <u>EXECUTIVE SUMMARY</u></p>
                <p>The internal stakeholders meeting for the Responsible Computing (RC) project at Dedan Kimathi University of Technology served as a pivotal platform for fostering collaboration, dialogue, and reflection on the integration of responsible computing principles into academic curricula and professional practice. Led by the Dean of the School of Computer Science & Information Technology, the meeting brought together faculty members, students, and industry experts to discuss key issues related to responsible computing, ethics, and their implications for education and practice in the field of computer science. Throughout the meeting, participants engaged in thought-provoking discussions and shared valuable insights and recommendations on topics such as comprehensive course coverage, industry tests on skills, causes of cheating, advancements in technology, evolving technology and social impact, early concepts vs. today's technology, and fighting cybersecurity. Key recommendations emerged, including the need for enhanced curriculum integration, expanded mentorship programs, development of practical tools and resources, promotion of ethical leadership, community engagement and outreach, and evaluation and continuous improvement. Moving forward, the insights and recommendations gathered from the stakeholders meeting will inform the continued development and implementation of the RC project, ensuring its relevance and impact in shaping a more responsible computing community at Dedan Kimathi University of Technology and beyond.</p>

                <h2 class="fw-bold">1. Introduction and Registration of Members:</h2>
                <p>The internal stakeholders meeting held as part of the Responsible Computing (RC) project at Dedan Kimathi University of Technology served as a pivotal gathering to gather feedback, insights, and recommendations from staff and students involved in the project. With the aim of fostering responsible computing practices within the academic community, the meeting provided a platform for meaningful dialogue and collaboration among stakeholders. The meeting sought to address various aspects of responsible computing, ethics, and their integration into the academic curriculum, with the overarching goal of promoting ethical awareness and responsible conduct in computing education and practice.</p>
                <p>Against the backdrop of rapid technological advancements and their increasing impact on society, the need for ethical considerations in computing has never been more pronounced. Issues such as data privacy, algorithmic bias, cybersecurity, and digital rights have emerged as critical concerns, underscoring the importance of cultivating a culture of responsible computing within the academic community. The internal stakeholders meeting aimed to address these concerns by fostering a deeper understanding of the ethical dimensions of computing and exploring strategies for integrating responsible computing principles into academic curricula and professional practice.</p>
                <p>Led by the Dean of the School of Computer Science & Information Technology, the meeting began with a warm welcome and overview of the RC project's objectives and activities. Members were invited to introduce themselves, setting the stage for open and inclusive discussions. The meeting agenda included presentations, feedback sessions, and debates on various topics related to responsible computing, including guest speaker sessions, mentorship programs, curriculum development efforts, and ethical considerations in computing education and practice.</p>
                <p>The meeting also provided a platform for debating ethical dilemmas and emerging trends in technology, such as the impact of artificial intelligence on employment and the ethical considerations of AI use. Faculty members shared their perspectives on these issues, highlighting the need for ongoing dialogue and collaboration between academia, industry, and policymakers to address the ethical implications of technological advancements.</p>

                <p class="fw-bold">1.1 Welcome Note and Overview: </p>
                <p>A project member provided an overview of the RC project, emphasizing its objectives and key activities aimed at promoting responsible computing practices. These activities included a wide array of initiatives, including addressing RC issues, integrating responsible computing principles into the Computer Science (CS) curricula, organizing bootcamps, developing the Software Ethics Assessment Tool (SEAT), establishing the DeKUT RC and Ethics Club, implementing a mentorship program, and hosting career talks and guest speakers. Members were warmly encouraged to actively engage in the discussion and provide valuable feedback on these activities, fostering a participatory and inclusive environment where diverse perspectives could be shared and considered in shaping the future direction of the project.</p>

                <h2 class="fw-bold">2. Feedback Session from Students: </h2>
                <p>During the feedback session, several students shared their experiences and insights gained from participating in the RC project. Vanessa, the club's treasurer, expressed gratitude for the project, describing it as an eye-opener and impactful experience. She highlighted the value of guest speaker sessions from industry leaders, such as those from the IEBC and FLEXPAY, in integrating Responsible Computing and ethics in real-world settings. Vanessa also noted the gradual progress of the mentorship program, despite some delays.</p>
                <p>Another club member echoed Vanessa's sentiments, thanking the school for initiating the project and acknowledging the challenges faced, particularly in the mentorship program. However, they expressed appreciation for the volunteer mentors who have supported students throughout the program. The club's chairperson, Clint Simiyu, demonstrated a deep understanding of RC concepts and their practical application in CS projects. He emphasized the importance of ethical considerations and highlighted the use of tools like the SEAT in guiding project development.</p>
                <p>Clint shared insights from his team's experience with the SEAT during project presentations, noting its effectiveness as a framework for integrating RC principles. He also discussed the integration of RC principles into specific projects, such as the Evote project, citing examples such as sustainability, community engagement, and bias mitigation. Additionally, Clint mentioned his initiative to start a blog on Medium.com to raise awareness about ethical issues in technology, such as the unauthorized use of user data in applications.</p>
                <p>Other club members shared their positive experiences with the project, emphasizing its impact on their career development and ethical awareness. A total of nine students had the opportunity to present their experiences on various aspects of RC concepts, mentorship, career talks, and bootcamps.</p>
                <p class="fw-bold">2.1 Feedback Session from Faculty: </p>
                <p>The faculty feedback session commenced with a thought-provoking question posed by the Dean regarding exam cheating and ethics. This sparked a lively debate among students and faculty, delving into various ethical considerations and challenges in education and technology.</p>

                <p class="fw-bold">2.1.1 Comprehensive Course Coverage: </p>
                <p>Faculty members emphasized the critical importance of comprehensive course coverage in effectively integrating Responsible Computing and ethics into the academic curriculum. They underscored the need for a robust value system that prioritizes ethical conduct and responsible practices, recognizing that progress in this regard may initially be slow. It was noted that ensuring that ethical considerations are thoroughly integrated into course materials and learning objectives across various disciplines within the curriculum, students can develop a deeper understanding of the ethical dimensions of computing and their implications for society. Moreover, faculty members stressed the importance of fostering a culture of integrity, transparency, and accountability within academic institutions to reinforce ethical principles and promote responsible behavior among students and professionals in the field. Through thoughtful curriculum design and implementation, institutions can cultivate a new generation of ethical leaders and innovators who are equipped to address the complex ethical challenges of the digital age.</p>

                <p class="fw-bold">2.1.2 Industry Tests on Skills: </p>
                <p>A concern raised by faculty members was the disconnect between classroom learning and industry demands. They stressed the importance of aligning educational objectives with real-world skills to bridge this gap effectively.</p>
                <p>Faculty members expressed concern about the significant disconnect between classroom learning and the skillsets demanded by the industry. They highlighted the critical need to align educational objectives with the practical skills required in real-world professional settings to bridge this gap effectively. They noted that by ensuring that academic curricula are designed to equip students with the relevant knowledge, technical proficiency, and problem-solving abilities demanded by employers, educational institutions can better prepare graduates for success in the workforce. This alignment requires ongoing collaboration between academia and industry to identify emerging trends, technological advancements, and evolving job roles, thereby ensuring that educational programs remain relevant and responsive to the needs of the labor market. Additionally, integrating practical, hands-on learning experiences, such as internships, co-op programs, and industry partnerships, can further enhance students' readiness for employment and facilitate a smoother transition from academia to the workplace.</p>
                <p class="fw-bold">2.1.3 Causes of Cheating: </p>
                <p>During the meeting, a faculty member, possessing expertise in Ethics & Integrity/anti-corruption consultancy, delved into the root causes of cheating prevalent among students. He highlighted various factors contributing to academic dishonesty, including motivated offense, lack of guardianship, and the presence of a victim. He emphasized that the school should identify the underlying causes, underscoring the importance of introducing comprehensive ethics and integrity education initiatives within academic institutions. Such programs can play a pivotal role in addressing these issues effectively by instilling a strong ethical foundation among students, promoting a culture of academic honesty, and fostering a sense of personal responsibility. Moreover, integrating ethics and integrity education into the academic curriculum can empower students with the knowledge and skills necessary to navigate ethical dilemmas ethically and responsibly, thereby promoting integrity and ethical conduct in academic and professional settings.</p>
                <p class="fw-bold">2.1.4 Advancement in Technology: </p>

                <p>During the meeting, faculty members engaged in a discussion regarding advancements in technology and their implications for ethical considerations. They raised thought-provoking questions about whether the rapid advancement of technology has effectively removed fear from human behavior. This inquiry prompted reflections on the evolving relationship between humans and technology, with participants emphasizing the importance of acknowledging and addressing the human factor in technology development. While technological advancements offer unprecedented opportunities for innovation and progress, they also pose significant ethical challenges and risks. Recognizing the inherent complexities of human-technology interactions, educators, policymakers, and industry leaders can work collaboratively to develop responsible and ethical frameworks for technology development and deployment. Additionally, fostering a deeper understanding of the ethical implications of technology among students and professionals can help cultivate a more conscientious approach to innovation and technological advancement, ensuring that technology serves humanity's best interests while mitigating potential harms.</p>

                <p class="fw-bold">2.1.5 Evolving Technology and Social Impact: </p>
                <p>Concerns were raised about the evolving nature of technology and its social impact. Faculty members noted that ethical considerations may vary across different contexts and emphasized the importance of ethical reflection and critical thinking in navigating these complexities.</p>
                <p>During the meeting, faculty members voiced concerns regarding the evolving nature of technology and its broader social impact. They highlighted the dynamic and multifaceted nature of ethical considerations in technology, noting that ethical dilemmas may vary across different contexts and applications. Emphasizing the importance of ethical reflection and critical thinking, participants underscored the need for individuals to navigate these complexities thoughtfully and responsibly. Fostering a deeper understanding of the ethical implications of technology and promoting ethical awareness among students and professionals, academic institutions can empower individuals to make informed decisions and navigate ethical challenges effectively. Additionally, initiatives that encourage interdisciplinary collaboration and dialogue can facilitate a more holistic approach to addressing the social, ethical, and technological dimensions of contemporary issues. Through ongoing engagement and education, stakeholders can work together to promote ethical innovation and ensure that technology serves the best interests of society as a whole.</p>

                <p class="fw-bold">2.1.6 Early Concepts vs. Today’s Technology: </p>
                <p>As the meeting progressed, a faculty member from the School of Science drew attention to the evolution of technology and its ethical implications. He contrasted early concepts, such as the use of calculators in education, with contemporary technological advancements. The faculty member also highlighted ethical issues associated with modern technologies, citing examples such as fraudulent insurance claims. Discussing these examples, he underscored the importance of a robust value system in addressing the ethical challenges posed by technology. A value system that prioritizes integrity, transparency, and accountability can provide a framework for ethical decision-making and guide individuals in navigating complex ethical dilemmas. Moreover, integrating ethical considerations into technological development and deployment processes can help mitigate potential risks and ensure that technology is used responsibly to benefit society. Through ongoing dialogue and collaboration, stakeholders can work together to promote ethical awareness and foster a culture of responsible innovation in technology.</p>

                <p class="fw-bold">2.1.7 Fighting Cyber Security:</p>
                <p>Finally, faculty members engaged in a discussion regarding cybersecurity challenges and the imperative of integrating Responsible Computing and ethics into academic curricula. They emphasized that addressing cybersecurity challenges necessitates a comprehensive, multi-faceted approach that goes beyond technical solutions. Integrating Responsible Computing and ethics into curricula was underscored as a crucial step in preparing students to tackle these challenges effectively. Providing students with a foundational understanding of ethical principles and responsible practices in computing, academic institutions can equip them with the knowledge and skills needed to navigate cybersecurity dilemmas ethically and responsibly. Additionally, faculty members highlighted the importance of education and development initiatives in fostering a cybersecurity-aware culture within academic institutions and beyond. Through collaborative efforts and ongoing education, stakeholders can work together to address cybersecurity challenges and promote a safer and more secure digital environment for all.</p>
                <h2 class="fw-bold">3. Conclusion:</h2>

                <p>In conclusion, the internal stakeholders served as a pivotal platform for fostering collaboration, dialogue, and reflection on the integration of responsible computing principles into academic curricula and professional practice. Through engaging presentations, discussions, and feedback sessions, participants gained valuable insights into the importance of ethical considerations in computing and explored strategies for promoting responsible conduct in the field.</p>
                <p>The meeting underscored the significance of initiatives such as guest speaker sessions, mentorship programs, and curriculum development efforts in cultivating a culture of responsible computing within the academic community. Students expressed appreciation for the opportunities provided by the RC project to enhance their understanding of ethical principles and their application in real-world settings. Faculty members shared valuable perspectives on the challenges and opportunities associated with integrating responsible computing into academic curricula, highlighting the importance of comprehensive course coverage and the establishment of a value system within the curriculum.</p>
                <h2 class="fw-bold">4. Recommendations:</h2>
                <p>Stakeholders made further recommendations for sustainability of the project.</p>
                <p class="fw-bold">1. Continued Engagement and Collaboration:</p>
                <p>The RC project should prioritize ongoing engagement and collaboration with internal and external stakeholders, including students, faculty members, industry partners, and policymakers. Regular meetings, workshops, and forums should be organized to facilitate dialogue, share best practices, and address emerging issues related to responsible computing.</p>

                <p class="fw-bold">2. Enhanced Curriculum Integration: </p>
                <p>Efforts to integrate responsible computing principles into the academic curriculum should be further strengthened and expanded. This includes revising existing courses to incorporate relevant ethical considerations and developing new courses focused specifically on responsible computing. Faculty members should receive training and support to effectively teach these topics and integrate them into their course materials.</p>
                <p class="fw-bold">3. Expansion of Mentorship Programs: </p>
                <p>The mentorship program established as part of the RC project should be expanded to provide more opportunities for students to receive guidance and support from experienced professionals in the field. Mentorship activities should be structured to include practical experiences, networking opportunities, and career development advice tailored to the needs of individual students.</p>

                <p class="fw-bold">4. Development of Practical Tools and Resources</p>
                <p>The development of practical tools and resources, such as the Software Ethics Assessment Tool (SEAT), should be continued and expanded to support students and professionals in integrating responsible computing principles into their work. These tools should be user-friendly, accessible, and adaptable to different contexts, enabling users to assess and address ethical issues effectively.</p>
                <p class="fw-bold">5. Promotion of Ethical Leadership: </p>
                <p>The RC project should prioritize the promotion of ethical leadership among students and professionals in the field of computing. This includes fostering a culture of accountability, transparency, and integrity within academic institutions and workplaces, as well as providing opportunities for students to develop leadership skills and ethical decision-making abilities.</p>
                <p class="fw-bold">6. Community Engagement and Outreach: </p>
                <p>Efforts to promote responsible computing should extend beyond the academic community to engage with the broader public. This includes organizing outreach events, workshops, and educational campaigns to raise awareness about the importance of ethical considerations in computing and empower individuals to make responsible choices in their use of technology.</p>
                <p class="fw-bold">7. Evaluation and Continuous Improvement: </p>
                <p>The RC project should establish mechanisms for evaluating its impact and effectiveness over time. This includes collecting feedback from stakeholders, monitoring key performance indicators, and conducting regular assessments of student learning outcomes and ethical behavior. Based on these evaluations, the project should identify areas for improvement and make adjustments as needed to ensure its continued success.</p>
                <hr>
                <strong>DeKUT RC Project | (Send feedback to rc@dkut.ac.ke)</strong>
            </div>

        </div>

    </div>
</div>

<?php
// index.php or other_php_files.php

// Include the footer.php file
include 'partials/footer.php';
?>